// src/routes/posts.svelte
<script lang="ts">
    import type { CohostPost } from "./types";
    export let posts: CohostPost[] ;
</script>
<div class="posts">
    <ul class="postList">
        {#each posts as x}
            <li class="post">
                <a style="text-decoration:none;" href={x.url}><h4>{x.title}</h4></a>
                <div>{@html x.content_html}</div>
                <p style="color:pink;">Posted {
                    new Date(x.date_modified)
                    .toLocaleDateString('en-au', {
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    })
                }</p>
                <ul class="tags">
                    {#each x.tags as tag}
                        <a href={"https://cohost.org/jmsfbs/tagged/"+tag}><li>#{tag}</li></a>
                    {/each}
                </ul>
            </li>
        {/each}
    </ul>
    <a class="readMore" href="https://cohost.org/jmsfbs"><p>Read More Posts</p></a>
</div>
<style>
.posts {
    display: grid;
    min-height: 10em;
    gap: 1em;
}

.posts .postList {
    list-style: none;
    display: grid;
    gap: 5em;
}


.post :global(div), .post :global(figure) {
    display: grid;
}

.post :global(img) {
    max-width: 100%;
    margin: 0em;
    box-sizing: border-box;
}

.post :global(img) {
    border-radius: 0.25em;
    border: solid 5px white;
    margin: 1em 0em;
}

.post :global(h1), .post :global(h2), .post :global(h3), .post :global(h4) {
    margin: 0em;
}

.post {
    background-color: black;
    padding: 1em 1em 2em 1em;
    border-radius: 0.2;
    max-width: 40em;
}

li.post {
    padding: 1em;
}

.post h4:first-child {
    border-bottom: solid 5px #c0ffd9;
    border-left: solid 6px #10d0ff;
    padding: 1em;

    width: calc(100% + 2em);
    left: -1em;
    top: -1em;
    position: relative;
    box-sizing: border-box;
}

@media (max-width: 800px) {
    .posts {
        display: none;
    }
}

.tags {
    list-style: none;
    padding-left: 0px;
    display: flex;
    gap: 0.5em;
    flex-wrap: wrap;
}

.readMore {
    text-align: center;
    padding-top: 5em;
}
</style>

// src/components/posts.tsx
import { createSignal, createResource, Show, For } from "solid-js";
import style from './posts.module.css'

const feedURL = '/feed/cohost.json'

const example = {
    "id": "915980",
    "content_html": "",
    "url": "https://cohost.org/jmsfbs/post/915980-starting-the-next-so",
    "title": "Starting the next song",
    "summary": "",
    "date_modified": "2023-01-27T06:56:51.650Z",
    "date_published": "2023-01-27T06:56:51.647Z",
    "author": {
      "name": "@jmsfbs",
      "url": "https://cohost.org/jmsfbs"
    },
    "tags": [
      "Midi",
      "home recording",
      "songwriting"
    ]
}
type CohostPost = typeof example;

async function fetchFeed(){
    const res = await fetch(feedURL).then( x => x.ok ? x.json() : Promise.reject([x.statusText]) )
    const { items } = res as ({ items: CohostPost[] })

    
    return items
        .filter( 
            x => (
                x.tags.includes('music') 
                || x.tags.includes('home recording')
            )
            && x.author.name === '@jmsfbs'
        )
        .slice(0,10)
}

export default () => {
    const [now] = createSignal(Date.now())
    const [feed] = createResource(now, fetchFeed)

    return (
        <div class={style.posts}>
            <Show when={feed.state== 'ready'} fallback={null}>
                <ul class={style.postList}>
                    <For each={feed()}>
                        { x => 
                        <li class={style.post}>    
                            <h4>{x.title}</h4>
                            <div innerHTML={x.content_html}></div>
                            <p style="color:pink;">Posted {
                                new Date('2019-07-31')
                                .toLocaleDateString(window.navigator.language, {
                                    year: 'numeric',
                                    month: 'long',
                                    day: 'numeric'
                                })
                            }</p>
                            <ul class={style.tags}>{
                                x.tags.map( x => <a href={"https://cohost.org/jmsfbs/tagged/"+x}><li>#{x}</li></a>)
                            }</ul>
                        </li>
                            
                        }
                    </For>
                </ul>
                <a class={style.readMore} href="https://cohost.org/jmsfbs"><p>Read More Posts</p></a>
            </Show>
        </div>
        
    )
}
